package com.taozi.fanyi.model.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	public java.lang.String getUserName() {
		return get("user_name");
	}

	public void setUserPass(java.lang.String userPass) {
		set("user_pass", userPass);
	}

	public java.lang.String getUserPass() {
		return get("user_pass");
	}

	public void setUserType(java.lang.String userType) {
		set("user_type", userType);
	}

	public java.lang.String getUserType() {
		return get("user_type");
	}

}
