package com.taozi.fanyi.model.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseException<M extends BaseException<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setAuthorityId(java.lang.Integer authorityId) {
		set("authority_id", authorityId);
	}

	public java.lang.Integer getAuthorityId() {
		return get("authority_id");
	}

	public void setExptType(java.lang.String exptType) {
		set("expt_type", exptType);
	}

	public java.lang.String getExptType() {
		return get("expt_type");
	}

}
