package com.taozi.fanyi.model.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAuthority<M extends BaseAuthority<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setActionKey(java.lang.String actionKey) {
		set("action_key", actionKey);
	}

	public java.lang.String getActionKey() {
		return get("action_key");
	}

}
