package com.taozi.fanyi.model.models;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("authentication", "id", Authentication.class);
		arp.addMapping("authority", "id", Authority.class);
		arp.addMapping("biz_topic", "id", BizTopic.class);
		arp.addMapping("exception", "id", Exception.class);
		arp.addMapping("mask", "id", Mask.class);
		arp.addMapping("role", "id", Role.class);
		arp.addMapping("user", "id", User.class);
	}
}

