package com.taozi.fanyi.model.models;

import com.taozi.fanyi.model.models.base.BaseAuthority;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Authority extends BaseAuthority<Authority> {
	public static final Authority dao = new Authority();
}
