package com.taozi.fanyi.model.models;

import com.taozi.fanyi.model.models.base.BaseAuthentication;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Authentication extends BaseAuthentication<Authentication> {
	public static final Authentication dao = new Authentication();
}
