package com.taozi.fanyi.model.models;

import com.taozi.fanyi.model.models.base.BaseBizTopic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BizTopic extends BaseBizTopic<BizTopic> {
	public static final BizTopic dao = new BizTopic();
}
