package com.taozi.fanyi.model.models;

import com.taozi.fanyi.model.models.base.BaseException;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Exception extends BaseException<Exception> {
	public static final Exception dao = new Exception();
}
