package com.taozi.fanyi.model.models;

import com.taozi.fanyi.model.models.base.BaseMask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mask extends BaseMask<Mask> {
	public static final Mask dao = new Mask();
}
