package com.taozi.fanyi.model.models;

import com.taozi.fanyi.model.models.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role();
}
