package com.taozi.fanyi.model.models;

import com.taozi.fanyi.model.models.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
}
