package com.taozi.fanyi.model.models;

import com.jfinal.plugin.activerecord.Db;
import com.taozi.fanyi.model.models.base.BaseUser;
import com.taozi.fanyi.utils.encrypt.Encryptor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
	
	public long getCount() {
		return Db.queryLong("select count(id) from user where email = ? and user_pass = ?", getEmail(), Encryptor.base64AfterMd5(getUserPass()));
	}
	
	public User getSignInUser() {
		return User.dao.findFirst("select * from user where email = ? and user_pass = ?", getEmail(), Encryptor.base64AfterMd5(getUserPass()));
	}
	
}
